#### Subscribers ########
subscribers:
  alphasense_front_rgb:
    fusion: ['image_color']
    topic_name_camera: /alphasense_driver_ros/cam4/debayered
    topic_name_camera_info: /alphasense_driver_ros/cam4/camera_info
    channels: ["rgb_image"]
    data_type: image
  
  alphasense_left_rgb:
    fusion: ['image_color']
    topic_name_camera: /alphasense_driver_ros/cam3/debayered
    topic_name_camera_info: /alphasense_driver_ros/cam3/camera_info
    channels: ["rgb_image"]
    data_type: image


  alphasense_right_rgb:
    fusion: ['image_color']
    topic_name_camera: /alphasense_driver_ros/cam5/debayered
    topic_name_camera_info: /alphasense_driver_ros/cam5/camera_info
    channels: ["rgb_image"]
    data_type: image

  wvn_front_traversability:
    fusion: ['image_exponential']
    topic_name_camera: '/wild_visual_navigation_node/front/traversability'
    topic_name_camera_info: '/wild_visual_navigation_node/front/camera_info'
    channels: ["visual_traversability"]
    data_type: image
  
  # wvn_left_traversability:
  #   fusion: ['image_exponential']
  #   topic_name_camera: '/wild_visual_navigation_node/left/traversability'
  #   topic_name_camera_info: '/wild_visual_navigation_node/left/camera_info'
  #   channels: ["visual_traversability"]
  #   data_type: image
  
  # wvn_right_traversability:
  #   fusion: ['image_exponential']
  #   topic_name_camera: '/wild_visual_navigation_node/right/traversability'
  #   topic_name_camera_info: '/wild_visual_navigation_node/right/camera_info'
  #   channels: ["visual_traversability"]
  #   data_type: image
  
  wvn_front_confidence:
    fusion: ['image_exponential']
    topic_name_camera: '/wild_visual_navigation_node/front/confidence'
    topic_name_camera_info: '/wild_visual_navigation_node/front/camera_info'
    channels: ["visual_confidence"]
    data_type: image
  
  # wvn_left_confidence:
  #   fusion: ['image_exponential']
  #   topic_name_camera: '/wild_visual_navigation_node/left/confidence'
  #   topic_name_camera_info: '/wild_visual_navigation_node/left/camera_info'
  #   channels: ["visual_confidence"]
  #   data_type: image
  
  # wvn_right_confidence:
  #   fusion: ['image_exponential']
  #   topic_name_camera: '/wild_visual_navigation_node/right/confidence_raw'
  #   topic_name_camera_info: '/wild_visual_navigation_node/right/camera_info'
  #   channels: ["visual_confidence"]
  #   data_type: image

  front_bpearl:
    channels: []
    fusion: []
    topic_name: /robot_self_filter/bpearl_front/point_cloud
    data_type: pointcloud

  rear_bpearl:
    channels: []
    fusion: []
    topic_name: /robot_self_filter/bpearl_rear/point_cloud
    data_type: pointcloud
  
  front_depth:
    channels: []
    fusion: []
    topic_name: /depth_camera_front/point_cloud_self_filtered
    data_type: pointcloud

  rear_depth:
    channels: []
    fusion: []
    topic_name: /depth_camera_rear/point_cloud_self_filtered
    data_type: pointcloud

  left_depth:
    channels: []
    fusion: []
    topic_name: /depth_camera_left/point_cloud_self_filtered
    data_type: pointcloud

  right_depth:
    channels: []
    fusion: []
    topic_name: /depth_camera_right/point_cloud_self_filtered
    data_type: pointcloud
  
  velodyne:
    channels: []
    fusion: []
    topic_name: /point_cloud_filter/lidar/point_cloud_filtered
    data_type: pointcloud
