# Input topics
robot_state_topic: "/wild_visual_navigation_node/robot_state"
desired_twist_topic: "/motion_reference/command_twist"
# desired_twist_topic: "/log/state/desiredRobotTwist"

camera_topics:
  front:
    image_topic: "/alphasense_driver_ros/cam4/debayered/compressed"
    info_topic: "/alphasense_driver_ros/cam4/camera_info"
    use_for_training: true
  # left:
  #   image_topic: "/alphasense_driver_ros/cam3/debayered"
  #   info_topic: "/alphasense_driver_ros/cam3/camera_info"
  #   use_for_training: false
  # right:
  #   image_topic: "/alphasense_driver_ros/cam5/debayered"
  #   info_topic: "/alphasense_driver_ros/cam5/camera_info"
  #   use_for_training: false


# Relevant frames
fixed_frame: odom
base_frame: base
camera_frame: cam4_sensor_frame_helper
footprint_frame: footprint

# Robot size
robot_length: 1.0
robot_width: 0.6
robot_height: 0.3

# Robot specs
robot_max_velocity: 0.8

# Traversability estimation params
traversability_radius: 3.0 # meters
image_graph_dist_thr: 0.2 # meters
proprio_graph_dist_thr: 0.1 # meters
network_input_image_height: 224 # 448
network_input_image_width: 224 # 448
segmentation_type: "slic"
feature_type: "dino"
dino_patch_size: 16 # DINO only

# Optical flow params
optical_flow_estimator_type: "sparse"

# Supervision Generator
untraversable_thr: 0.01

# Threads
image_callback_rate: 3 # hertz
proprio_callback_rate: 4 # hertz
learning_thread_rate: 10 # hertz

# Runtime options
device: "cuda"
mode: "online" # check out comments in the class WVNMode
print_image_callback_time: true
print_proprio_callback_time: false
use_debug_for_desired: true
