# Input topics
robot_state_topic: "/wild_visual_navigation_node/robot_state"
image_topic: "/alphasense_driver_ros/cam4/debayered"
camera_info_topic: "/alphasense_driver_ros/cam4/camera_info"
#desired_twist_topic: "/log/state/desiredRobotTwist"
desired_twist_topic: "/motion_reference/command_twist"

# Relevant frames
fixed_frame: odom
base_frame: base
camera_frame: cam4_sensor_frame_helper
footprint_frame: footprint

# Robot size
robot_length: 1.0
robot_width: 0.6
robot_height: 0.3

# Robot specs
robot_max_velocity: 0.8

# Traversability estimation params
traversability_radius: 3.0 # meters
image_graph_dist_thr: 0.2 # meters
proprio_graph_dist_thr: 0.1 # meters
network_input_image_height: 224 # 448
network_input_image_width: 224 # 448
segmentation_type: "slic"
feature_type: "dino"
dino_patch_size: 16 # DINO only

# Optical flow params
optical_flow_estimator_type: "sparse"

# Supervision Generator
robot_max_velocity: 0.8
untraversable_thr: 0.01

# Threads
run_online_learning: true
image_callback_rate: 3 # hertz
proprio_callback_rate: 4 # hertz
learning_thread_rate: 10 # hertz

# Runtime options
device: "cuda"
mode: "default" # "online" for efficiency, "default" for debugging
print_image_callback_time: false
use_debug_for_desired: true


