visu: True
debug: True
rescale_orig: True
only_img: True

# Prediction parameters
threshold: 0.55  # 2000: 0.31, 500: 0.37 / 0.3
running_median_prior: 500  # 2000: 550, 500: 800
running_std_prior: 200  # 2000: 400, 500: 450

# Processing
img_size: 448
slic_num_components: 2000

# Plotting
unknown_interval: [-0.02, 0.02]  # Interval of predictions of unknown class
overlay_alpha: 0.35
color_safe: [0, 1, 0]
color_unsafe: [1, 0, 0]
color_unknown: [1.0, 0.6, 0.0]

# Input and output topics
img_input_topic: /wide_angle_camera_front/img_out # /wide_angle_camera_front/img_out # /alphasense_driver_ros/cam4/dropped/debayered/slow, /wide_angle_camera_front/image_color
info_input_topic: /wide_angle_camera_front/camera_info  # /wide_angle_camera_front/camera_info  # /wide_angle_camera_front/camera_info

info_output_topic: /wild_anomaly_detection/camera_info
bin_img_output_topic: /wild_anomaly_detection/bin_img
vis_img_output_topic: /wild_anomaly_detection/vis_img

# Weights
weights: all_train_2000_bs=500_eps=10_nf=10_top=200.pth # hoengg_2000.pth  # hoengg_2000.pth, hoengg_500.pth
