visu: True
debug: True
rescale_orig: True
only_img: False

# Prediction parameters
threshold: 0.45  # 45
loss_scaling: 0.01

# Processing
img_size: 448
slic_num_components: 2000

# Plotting
unknown_interval: [-0.02, 0.02]  # Interval of predictions of unknown class
overlay_alpha: 0.35
color_safe: [0, 1, 0]
color_unsafe: [1, 0, 0]
color_unknown: [1.0, 0.6, 0.0]

# Input and output topics
img_input_topic: /wide_angle_camera_front/img_out # /wide_angle_camera_front/img_out # /alphasense_driver_ros/cam4/dropped/debayered/slow, /wide_angle_camera_front/image_color
info_input_topic: /wide_angle_camera_front/camera_info  # /wide_angle_camera_front/camera_info  # /wide_angle_camera_front/camera_info

info_output_topic: /wild_anomaly_detection/camera_info
bin_img_output_topic: /wild_anomaly_detection/bin_img
vis_img_output_topic: /wild_anomaly_detection/vis_img

# Weights
weights: hoengg_1.pth  # hoengg_1.pth, hoengg_2.pth