camera_topics:
  front:
    image_topic: "/alphasense_driver_ros/cam4/debayered"
    info_topic: "/alphasense_driver_ros/cam4/camera_info"
    use_for_training: true
  # left:
  #   image_topic: "/alphasense_driver_ros/cam3/debayered"
  #   info_topic: "/alphasense_driver_ros/cam3/camera_info"
  #   use_for_training: false
  # right:
  #   image_topic: "/alphasense_driver_ros/cam5/debayered"
  #   info_topic: "/alphasense_driver_ros/cam5/camera_info"
  #   use_for_training: false

# Provides 1080 (height) x 1920 (width) images
network_input_image_height: 224 # 448
network_input_image_width: 224 # 448