camera_topics:
  front:
    image_topic: "/depth_camera_rear/color/image_raw"
    info_topic: "/depth_camera_rear/color/camera_info"
    use_for_training: true

# Provides 480 (height) x 848 (width) images
network_input_image_height: 224 # 448
network_input_image_width: 224 # 448