camera_topics:
  front:
    image_topic: "/wide_angle_camera_front/image_color"
    info_topic: "/wide_angle_camera_front/camera_info"
    use_for_training: true

# Provides 1080 (height) x 1920 (width) images
network_input_image_height: 224 # 448
network_input_image_width: 224 # 448